name: SQL Autograder
on: [push]

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install SQLite
        run: sudo apt-get install sqlite3

      - name: Recreate grader script from secret
        run: echo "$GRADER_SCRIPT" > grader.sh
        env:
          GRADER_SCRIPT: ${{ secrets.GRADER_SCRIPT }}

      - name: Run grader
        run: bash grader.sh
        env:
          INIT_SQL: ${{ secrets.INIT_SQL }}
          SOL_Q1: ${{ secrets.SOL_Q1 }}
